function print_info(dir, data, Pinfo, Fcoeff )
    for fld_ind = 1:numel(data)
    fname = [dir, 'JPF_', data{fld_ind}.fieldname,'.txt'];
    fid = fopen(fname, 'w');
    fprintf(fid, '%8s %8s %8s %8s %8s %8s %8s %8s %8s %8s %8s %8s %8s %8s %8s %8s %8s\n','#fied_CCD','source', 'alpha', 'Jind', 'R21', 'R31', 'phi21', 'phi31', 'P1', 'P2', 'P3', 'dP1', 'dP2', 'dP3','Conf1', 'Conf2','Conf3');
    [nobj, Nnights] = size(data{fld_ind}.MJD);
    for obj = 1:nobj
        fprintf(fid, ...
            '%8s %8i %8.4f %8.4f %8.4f %8.4f %8.4f %8.4f %8.4f %8.4f %8.4f %8.4f %8.4f %8.4f %8.4f %8.4f %8.4f\n',...
                data{fld_ind}.fieldname, ...
                data{fld_ind}.source(obj,1), ...
                data{fld_ind}.alphacorr, ...
                data{fld_ind}.Jinds(obj),...
                Fcoeff{fld_ind}.R21(obj), ...
                Fcoeff{fld_ind}.R31(obj), ...
                Fcoeff{fld_ind}.phi21(obj), ...
                Fcoeff{fld_ind}.phi31(obj), ...
                Pinfo{fld_ind}.peakperiods(obj,:), ...
                Pinfo{fld_ind}.peakperioderrs(obj,:), ...
                (1-Pinfo{fld_ind}.peakpower_falsealarm(obj,:))*100 ...
            );
    end
    fclose(fid);
    end
end